# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13904bb68a9d4e61b4cc6579b5a710df69dfc4d8940f4851c2c3193fc3fa9cda25ca4c4113fc92595959590f1935f883fee34f761351b5a4eb288e88fc10a2cb

test:
  secret_key_base: c80af45f7283573206c46a94f587e4e7751b177ff763b5183c390ae05f19647d5bdc39b5431c31553e1fb8ba75ba177343fea0f2914c3be013c6fc4d25b53aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
